//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TP2017Entities : DbContext
    {
        public TP2017Entities()
            : base("name=TP2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AnioLectivo> AnioLectivoes { get; set; }
        public DbSet<Asignatura> Asignaturas { get; set; }
        public DbSet<Aula> Aulas { get; set; }
        public DbSet<DetalleReserva> DetalleReservas { get; set; }
        public DbSet<Dia> Dias { get; set; }
        public DbSet<Docente> Docentes { get; set; }
        public DbSet<HistContrasenia> HistContrasenias { get; set; }
        public DbSet<NombreDia> NombreDias { get; set; }
        public DbSet<Periodo> Periodoes { get; set; }
        public DbSet<Reserva> Reservas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TipoAsignatura> TipoAsignaturas { get; set; }
        public DbSet<TipoAula> TipoAulas { get; set; }
        public DbSet<TipoPeriodo> TipoPeriodoes { get; set; }
        public DbSet<TipoPizarron> TipoPizarrons { get; set; }
        public DbSet<TipoReserva> TipoReservas { get; set; }
        public DbSet<TipoUsuario> TipoUsuarios { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
