//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.DetalleReservas = new HashSet<DetalleReserva>();
        }
    
        public int id_reserva { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<int> capacidad { get; set; }
        public Nullable<bool> activa { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_asignatura { get; set; }
        public Nullable<int> id_tipo_reserva { get; set; }
        public Nullable<int> id_docente { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReserva> DetalleReservas { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual TipoReserva TipoReserva { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
